"""empty message

Revision ID: 79600146a797
Revises: 46fc80201572
Create Date: 2020-11-01 16:44:21.267034

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '79600146a797'
down_revision = '46fc80201572'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('goods', 'price',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('goods', 'price',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
